SET FOREIGN_KEY_CHECKS = 0;
drop table advisor;
drop table campus;
drop table concentration;
drop table course;
drop table department;
drop table major;
drop table offline_course;
drop table online_course;
drop table professor;
drop table registration;
drop table student;
drop table ta;
drop table teaching;
drop table works_on;
drop view sea_advisor;
drop view bos_advisor;
drop view tor_advisor;
drop view svsf_advisor;
drop view cs_course;
drop PROCEDURE getCourseByType;
drop PROCEDURE getCourseWithCertainPrereq;
SET FOREIGN_KEY_CHECKS = 1;